slack_upload_reorg_priority_str = [
    "Priority upload (test_priority_project) reorganized:",
    "hubmap_id: <https://ingest.hubmapconsortium.org/upload/test_uuid|test_hm_id>",
    "created_by_user_displayname: Test User",
    "created_by_user_email: test@user.com",
    "dataset_type: test_dataset_type",
    "organ: test_organ",
    "priority_project_list: test_priority_project",
    "",
    "Datasets:",
    "hubmap_id,created_by_user_displayname,created_by_user_email,priority_project_list,dataset_type,organ,globus_link,filesystem_path",
    "test_dataset_hm_id, test user, test@user.com, test_priority_project, test_dataset_type, test_organ, <test_globus_url|Globus>, test_abs_path",
    "test_dataset_hm_id2, test user2, test@user2.com, test_priority_project, test_dataset_type2, test_organ, <test_globus_url|Globus>, test_abs_path",
]


slack_upload_reorg_str = [
    "Upload test_hm_id | test_uuid reorganized:",
    "hubmap_id: <https://ingest.hubmapconsortium.org/upload/test_uuid|test_hm_id>",
    "created_by_user_displayname: Test User",
    "created_by_user_email: test@user.com",
    "dataset_type: test_dataset_type",
    "organ: test_organ",
    "",
    "Datasets:",
    "hubmap_id,created_by_user_displayname,created_by_user_email,dataset_type,organ,globus_link,filesystem_path",
    "test_dataset_hm_id, test user, test@user.com, test_dataset_type, test_organ, <test_globus_url|Globus>, test_abs_path",
    "test_dataset_hm_id2, test user2, test@user2.com, test_dataset_type2, test_organ, <test_globus_url|Globus>, test_abs_path",
]

good_upload_context = {
    "uuid": "test_uuid",
    "hubmap_id": "test_hm_id",
    "created_by_user_displayname": "Test User",
    "created_by_user_email": "test@user.com",
    "group_name": "test group",
    "priority_project_list": ["test_priority_project"],
    "unrelated_field": True,
    "ingest_task": "existing ingest_task text",
    "validation_message": "existing validation_message text",
    "datasets": [
        {
            "uuid": "test_dataset_uuid",
            "hubmap_id": "test_dataset_hm_id",
            "entity_type": "Dataset",
            "created_by_user_displayname": "Test User",
            "created_by_user_email": "test@user.com",
            "priority_project_list": ["test_priority_project"],
            "dataset_type": "test_dataset_type",
            "metadata": [{"parent_dataset_id": "test_parent_id"}],
            "status": "Submitted",
        },
        {
            "uuid": "test_dataset_uuid2",
            "hubmap_id": "test_dataset_hm_id2",
            "entity_type": "Dataset",
            "created_by_user_displayname": "Test User2",
            "created_by_user_email": "test@user2.com",
            "priority_project_list": ["test_priority_project"],
            "dataset_type": "test_dataset_type2",
            "metadata": [{"parent_dataset_id": "test_parent_id"}],
            "status": "Submitted",
        },
    ],
    "status": "New",
    "entity_type": "Upload",
}

dataset_context_mock_value = {
    "uuid": "test_dataset_uuid",
    "hubmap_id": "test_hm_dataset_id",
    "created_by_user_displayname": "Test User",
    "created_by_user_email": "test_dataset@user.com",
    "status": "New",
    "entity_type": "Dataset",
    "creation_action": "Create Dataset Activity",
}

derived_dataset_context_mock_value = dataset_context_mock_value | {
    "creation_action": "Central Process"
}

dataset_context_mock_value_with_error = {
    "uuid": "test_dataset_uuid",
    "hubmap_id": "test_hm_dataset_id",
    "created_by_user_displayname": "Test User",
    "created_by_user_email": "test_dataset@user.com",
    "status": "New",
    "entity_type": "Dataset",
    "error_message": "includes test_derived",
}

endpoints = {
    "hubmap": {
        "PROD": {
            "entity_url": "https://entity.api.hubmapconsortium.org",
            "ingest_url": "vm004@hive.psc.edu",
        },
        "DEV": {"entity_url": "https://entity-api.dev.hubmapconsortium.org"},
    },
    "sennet": {
        "PROD": {"entity_url": "https://entity.api.sennetconsortium.org"},
        "DEV": {"entity_url": "https://entity-api.dev.sennetconsortium.org"},
    },
}

# validation_report = 'Data File Errors:\n  Recursively test all ome-tiff files for an assay-specific list of fields:\n  - \'/hive/hubmap/data/protected/Stanford University Bone Marrow TMC/f6aff8e28f2fc0ef22e71cbadc1f6f51/HUBMAP1_slide100_L/lab_processed/images/HUBMAP_H&E_Slide99_C31C1.ome.tiff\n    is not a valid OME.TIFF file: Failed to read OME XML.\'\n  - \'/hive/hubmap/data/protected/Stanford University Bone Marrow TMC/f6aff8e28f2fc0ef22e71cbadc1f6f51/HUBMAP1_slide100_R/lab_processed/images/HUBMAP_H&E_Slide99_C32C1.ome.tiff\n    is not a valid OME.TIFF file: Failed to read OME XML.\'\n  Recursively test all ome-tiff files for validity:\n  - "/hive/hubmap/data/protected/Stanford University Bone Marrow TMC/f6aff8e28f2fc0ef22e71cbadc1f6f51/HUBMAP1_slide100_L/lab_processed/images/HUBMAP_H&E_Slide99_C31C1.ome.tiff\\\n    \\ is not a valid OME.TIFF file: XMLSchemaDecodeError: attribute Color="(255, 0, 0)": invalid literal for int()\\\n    \\ with base 10: "(255, 0, 0)"\n  - "/hive/hubmap/data/protected/Stanford University Bone Marrow TMC/f6aff8e28f2fc0ef22e71cbadc1f6f51/HUBMAP1_slide100_R/lab_processed/images/HUBMAP_H&E_Slide99_C32C1.ome.tiff\\\n    \\ is not a valid OME.TIFF file: XMLSchemaDecodeError: attribute Color="(255, 0, 0)": invalid literal for int()\\\n    \\ with base 10: "(255, 0, 0)"\n'

validation_report_html_list = [
    "<ul>",
    "<li>Directory Errors:</li>",
    "<ul>",
    "<li>examples/dataset-examples/bad-scatacseq-data/upload/dataset-1 (as scatacseq-v0.0):</li>",
    "<ul>",
    "<li>Not allowed:</li>",
    "<ul>",
    "<li>not-the-file-you-are-looking-for.txt</li>",
    "<li>unexpected-directory/place-holder.txt</li>",
    "</ul>",
    "<li>Required but missing:</li>",
    "<ul>",
    "<li>[^/]+\\.fastq\\.gz</li>",
    "</ul>",
    "</ul>",
    "</ul>",
    "<li>Antibodies/Contributors Errors:</li>",
    "<ul>",
    "<li>examples/dataset-examples/bad-scatacseq-data/upload/scatacseq-metadata.tsv:</li>",
    "<ul>",
    '<li>On row(s) 2, column "contributors_path", error opening or reading value ".". Expected a TSV, but found a directory: examples/dataset-examples/bad-scatacseq-data/upload.</li>',
    "</ul>",
    "</ul>",
    "<li>Local Validation Errors:</li>",
    "<ul>",
    "<li>examples/dataset-examples/bad-scatacseq-data/upload/scatacseq-metadata.tsv (as scatacseq-v0):</li>",
    "<ul>",
    '<li>On row 2, column "sc_isolation_protocols_io_doi", value "" fails because it must be filled out.</li>',
    '<li>On row 2, column "library_construction_protocols_io_doi", value "" fails because it must be filled out.</li>',
    '<li>On row 2, column "protocols_io_doi", value "10.17504/fake" fails because it is an invalid DOI.</li>',
    "</ul>",
    "</ul>",
    "</ul>",
]

ext_error_formatted = [
    "HuBMAP Upload <a href='https://ingest.hubmapconsortium.org/Upload/test_uuid'>test_hm_id</a> has failed validation.",
    "",
    "<b>Validation details</b>",
    "The validation process starts by checking metadata TSVs and directory structures. If those checks pass, then certain individual file types (such as FASTQ and OME.TIFF files) are validated.",
    "",
    "<b>What to do next</b>",
    "If you have questions about your upload, please schedule an appointment with Data Curator Brendan Honick: https://calendly.com/bhonick-psc/.",
    "",
    "This email address is not monitored. If you have questions, please schedule with Brendan Honick or email ingest@hubmapconsortium.org.",
    "",
    "The error log is included below if you would like to make updates to your submission independently; it is not required for you to do so before contacting our Data Curation Team. Please email ingest@hubmapconsortium.org if you believe you have repaired all validation errors so that we can re-validate your submission.",
    "",
    'If your submission has "Spreadsheet Validator Errors," please use the <a href="https://metadatavalidator.metadatacenter.org/">Metadata Spreadsheet Validator</a> tool to correct them.',
    "",
    "<b>Validation error log</b>",
    *validation_report_html_list,
]

validation_error_dict = {
    "Directory Errors": {
        "examples/dataset-examples/bad-scatacseq-data/upload/dataset-1 (as scatacseq-v0.0)": {
            "Not allowed": [
                "not-the-file-you-are-looking-for.txt",
                "unexpected-directory/place-holder.txt",
            ],
            "Required but missing": ["[^/]+\\.fastq\\.gz"],
        }
    },
    "Antibodies/Contributors Errors": {
        "examples/dataset-examples/bad-scatacseq-data/upload/scatacseq-metadata.tsv": [
            'On row(s) 2, column "contributors_path", error opening or reading value ".". Expected a TSV, but found a directory: examples/dataset-examples/bad-scatacseq-data/upload.'
        ]
    },
    "Local Validation Errors": {
        "examples/dataset-examples/bad-scatacseq-data/upload/scatacseq-metadata.tsv (as scatacseq-v0)": [
            'On row 2, column "sc_isolation_protocols_io_doi", value "" fails because it must be filled out.',
            'On row 2, column "library_construction_protocols_io_doi", value "" fails because it must be filled out.',
            'On row 2, column "protocols_io_doi", value "10.17504/fake" fails because it is an invalid DOI.',
        ]
    },
}

ext_error = 'HuBMAP Upload <a href="https://ingest.hubmapconsortium.org/upload/test_uuid">test_hm_id</a> has failed validation.<br><br><b>Validation details</b><br>The validation process starts by checking metadata TSVs and directory structures. If those checks pass, then certain individual file types (such as FASTQ and OME.TIFF files) are validated.<br><br><b>What to do next</b><br>If you have questions about your upload, please schedule an appointment with Data Curator Brendan Honick (https://calendly.com/bhonick-psc/) or email ingest@hubmapconsortium.org. Do not respond to this email; this inbox is not monitored.<br><br>The error log is included below if you would like to make updates to your submission independently. It is not required for you to correct any errors before contacting our Data Curation Team. Please email ingest@hubmapconsortium.org if you believe you have repaired all validation errors so that we can re-validate your submission.<br><br>If your submission has "Spreadsheet Validator Errors," please use the <a href="https://metadatavalidator.metadatacenter.org/">Metadata Spreadsheet Validator</a> tool to correct them.<br><br><b>Validation error log</b><br><ul><li>Directory Errors:</li><ul><li>examples/dataset-examples/bad-scatacseq-data/upload/dataset-1 (as scatacseq-v0.0):</li><ul><li>Not allowed:</li><ul><li>not-the-file-you-are-looking-for.txt</li><li>unexpected-directory/place-holder.txt</li></ul><li>Required but missing:</li><ul><li>[^/]+\\.fastq\\.gz</li></ul></ul></ul><li>Antibodies/Contributors Errors:</li><ul><li>examples/dataset-examples/bad-scatacseq-data/upload/scatacseq-metadata.tsv:</li><ul><li>On row(s) 2, column "contributors_path", error opening or reading value ".". Expected a TSV, but found a directory: examples/dataset-examples/bad-scatacseq-data/upload.</li></ul></ul><li>Local Validation Errors:</li><ul><li>examples/dataset-examples/bad-scatacseq-data/upload/scatacseq-metadata.tsv (as scatacseq-v0):</li><ul><li>On row 2, column "sc_isolation_protocols_io_doi", value "" fails because it must be filled out.</li><li>On row 2, column "library_construction_protocols_io_doi", value "" fails because it must be filled out.</li><li>On row 2, column "protocols_io_doi", value "10.17504/fake" fails because it is an invalid DOI.</li></ul></ul></ul>'


########################
# test_email_providers #
########################

df = {
    0: {
        "_id": "114123c03189e2d9ca0587a9b1ede308",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.275651,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1752600066788,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM652.PMDG.682",
        "_source.last_modified_timestamp": 1765404061505,
        "_source.status": "QA",
        "_source.title": "PhenoCycler data from the uterus of a 22-year-old white female",
    },
    1: {
        "_id": "474f0b4a77083fe938cc9352cb9a9470",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.275651,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1752600069825,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM328.ZSPV.447",
        "_source.last_modified_timestamp": 1763410336669,
        "_source.status": "New",
        "_source.title": "PhenoCycler data from the uterus of a 22-year-old white female",
    },
    2: {
        "_id": "ffb964a87cd93bc110ba39884d7df42a",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.275651,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1752600070932,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM658.VMWF.882",
        "_source.last_modified_timestamp": 1763409994962,
        "_source.status": "Invalid",
        "_source.title": "PhenoCycler data from the uterus of a 22-year-old white female",
    },
    3: {
        "_id": "889a27e6521388e3553472fc9e14439d",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.275651,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1752600141867,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM654.VCSC.832",
        "_source.last_modified_timestamp": 1763409954996,
        "_source.status": "Error",
        "_source.title": "PhenoCycler data from the uterus of a 34-year-old white female",
    },
    4: {
        "_id": "34d9bf4b4ecdb5a5e63f77744cb11175",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.275651,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1748623730486,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM375.RMJM.622",
        "_source.last_modified_timestamp": 1748631379142,
        "_source.status": "QA",
        "_source.title": "PhenoCycler data from the skin of a 30-year-old unknown female",
    },
    5: {
        "_id": "4aa0b85627ee40110c81648fdbc3f822",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.275651,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1747157593370,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM245.PVCT.423",
        "_source.last_modified_timestamp": 1747335999435,
        "_source.status": "QA",
        "_source.title": "PhenoCycler data from the skin of a 62-year-old unknown female",
    },
    6: {
        "_id": "cb9ceb9961874216557c6f76f4b97234",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.275651,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1749477294071,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM233.JWQF.322",
        "_source.last_modified_timestamp": 1763411064661,
        "_source.status": "QA",
        "_source.title": "PhenoCycler data from the skin of a 54-year-old unknown female",
    },
    7: {
        "_id": "c267d79eff73b466c729b9e5c0e030fd",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.275651,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1747157598755,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM878.KZGH.246",
        "_source.last_modified_timestamp": 1747239525873,
        "_source.status": "QA",
        "_source.title": "PhenoCycler data from the skin of a 43-year-old unknown male",
    },
    8: {
        "_id": "9650f5829651d7a8baf66d6c871d0210",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.275651,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1748623716218,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM544.DVKS.984",
        "_source.last_modified_timestamp": 1748631503950,
        "_source.status": "QA",
        "_source.title": "PhenoCycler data from the skin of a 43-year-old unknown male",
    },
    9: {
        "_id": "ad677611dba1b706d0041eb808599e19",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.275651,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1752600077586,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM954.NBFJ.868",
        "_source.last_modified_timestamp": 1765404107541,
        "_source.status": "QA",
        "_source.title": "PhenoCycler data from the uterus of a 33-year-old white female",
    },
    10: {
        "_id": "dec7bb7e8c291eb311f7a275af43f255",
        "_index": "hm_prod_consortium_portal",
        "_score": 8.047309,
        "_type": "_doc",
        "_source.created_by_user_email": "hubmap@hubmapconsortium.org",
        "_source.created_timestamp": 1752600068762,
        "_source.creation_action": "Create Dataset Activity",
        "_source.dataset_type": "PhenoCycler",
        "_source.entity_type": "Dataset",
        "_source.group_name": "Beth Israel Deaconess Medical Center TMC",
        "_source.group_uuid": "300ac006-547c-11ed-ab8d-fb258a2766ef",
        "_source.hubmap_id": "HBM496.VDKK.797",
        "_source.last_modified_timestamp": 1763410203934,
        "_source.status": "QA",
        "_source.title": "PhenoCycler data from the uterus of a 22-year-old white female",
    },
}
dp_instructions = [
    "<br>",
    "<b>What you can do to move datasets forward:</b><br>",
    "Some dataset statuses indicate the need for intervention by the data provider. Below are some brief instructions by status.<br>",
    "<ul>",
    "<li>QA: 8</li>",
    "The dataset has been validated and is ready for your approval. After reviewing these datasets, please email ingest@hubmapconsortium.org to list any datasets with issues that need to be addressed before publishing and/or indicate your approval of specific datasets for publication. Please include relevant dataset IDs in your message.<br>",
    "<ul>",
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/c267d79eff73b466c729b9e5c0e030fd">HBM878.KZGH.246</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/4aa0b85627ee40110c81648fdbc3f822">HBM245.PVCT.423</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/34d9bf4b4ecdb5a5e63f77744cb11175">HBM375.RMJM.622</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/9650f5829651d7a8baf66d6c871d0210">HBM544.DVKS.984</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/cb9ceb9961874216557c6f76f4b97234">HBM233.JWQF.322</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/dec7bb7e8c291eb311f7a275af43f255">HBM496.VDKK.797</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/114123c03189e2d9ca0587a9b1ede308">HBM652.PMDG.682</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/ad677611dba1b706d0041eb808599e19">HBM954.NBFJ.868</a></li>',
    "</ul>",
    "<br>",
    "<li>Invalid: 1</li>",
    "The dataset cannot be validated due a metadata or directory issue. View the errors on the dataset ingest page and correct them. Help is available by scheduling with Data Curator Brendan Honick (https://calendly.com/bhonick-psc/).<br>",
    "<ul>",
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/ffb964a87cd93bc110ba39884d7df42a">HBM658.VMWF.882</a></li>',
    "</ul>",
    "<br>",
    "<li>New: 1</li>",
    'This status is an artifact of prior status handling. Go to the dataset ingest page and press "Submit."<br>',
    "<ul>",
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/474f0b4a77083fe938cc9352cb9a9470">HBM328.ZSPV.447</a></li>',
    "</ul>",
    "<br>",
    "</ul>",
]

dp_other_counts = [
    "<br>",
    "<b>Datasets currently in the ingestion process:</b><br>",
    "Below are counts of datasets not currently requiring action on your part, with a brief description of each status.<br>",
    "<ul>",
    "<li>Error: 1</li>",
    "Datasets have encountered an internal HIVE error. Curators and developers are working to address the issue.<br>",
    "<ul>",
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/889a27e6521388e3553472fc9e14439d">HBM654.VCSC.832</a></li>',
    "</ul>",
    "<br>",
    "</ul>",
]

annotated_invalid = [
    "<br>",
    "<b>test title:</b><br>",
    "test_desc<br>",
    "<ul>",
    "<li>QA: 8</li>",
    "The dataset has been validated and is ready for your approval. After reviewing these datasets, please email ingest@hubmapconsortium.org to list any datasets with issues that need to be addressed before publishing and/or indicate your approval of specific datasets for publication. Please include relevant dataset IDs in your message.<br>",
    "<ul>",
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/c267d79eff73b466c729b9e5c0e030fd">HBM878.KZGH.246</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/4aa0b85627ee40110c81648fdbc3f822">HBM245.PVCT.423</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/34d9bf4b4ecdb5a5e63f77744cb11175">HBM375.RMJM.622</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/9650f5829651d7a8baf66d6c871d0210">HBM544.DVKS.984</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/cb9ceb9961874216557c6f76f4b97234">HBM233.JWQF.322</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/dec7bb7e8c291eb311f7a275af43f255">HBM496.VDKK.797</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/114123c03189e2d9ca0587a9b1ede308">HBM652.PMDG.682</a></li>',
    '<li><a href="https://ingest.hubmapconsortium.org/Dataset/ad677611dba1b706d0041eb808599e19">HBM954.NBFJ.868</a></li>',
    "</ul>",
    "<br>",
    "</ul>",
]

formatted_group_data = '<b>Biweekly unpublished dataset report for Beth Israel Deaconess Medical Center TMC</b><br>This report is sent to the group PIs, PMs, and all creators of datasets in this list.<br><br>If you have questions, please schedule an appointment with Data Curator Brendan Honick (https://calendly.com/bhonick-psc/) or email ingest@hubmapconsortium.org. Do not respond to this email; this inbox is not monitored.<br><br><b>Unpublished datasets:</b> 11<br>You can see more details about all datasets in the attached CSV file.<br><br>The datasets listed below are primary datasets representing the raw data that your site has submitted to the HIVE. Primary datasets can be published in advance of HIVE central analysis processing.<br><br><b>What you can do to move datasets forward:</b><br>Some dataset statuses indicate the need for intervention by the data provider. Below are some brief instructions by status.<br><ul><li>QA: 8</li>The dataset has been validated and is ready for your approval. After reviewing these datasets, please email ingest@hubmapconsortium.org to list any datasets with issues that need to be addressed before publishing and/or indicate your approval of specific datasets for publication. Please include relevant dataset IDs in your message.<br><ul><li><a href="https://ingest.hubmapconsortium.org/Dataset/c267d79eff73b466c729b9e5c0e030fd">HBM878.KZGH.246</a></li><li><a href="https://ingest.hubmapconsortium.org/Dataset/4aa0b85627ee40110c81648fdbc3f822">HBM245.PVCT.423</a></li><li><a href="https://ingest.hubmapconsortium.org/Dataset/34d9bf4b4ecdb5a5e63f77744cb11175">HBM375.RMJM.622</a></li><li><a href="https://ingest.hubmapconsortium.org/Dataset/9650f5829651d7a8baf66d6c871d0210">HBM544.DVKS.984</a></li><li><a href="https://ingest.hubmapconsortium.org/Dataset/cb9ceb9961874216557c6f76f4b97234">HBM233.JWQF.322</a></li><li><a href="https://ingest.hubmapconsortium.org/Dataset/dec7bb7e8c291eb311f7a275af43f255">HBM496.VDKK.797</a></li><li><a href="https://ingest.hubmapconsortium.org/Dataset/114123c03189e2d9ca0587a9b1ede308">HBM652.PMDG.682</a></li><li><a href="https://ingest.hubmapconsortium.org/Dataset/ad677611dba1b706d0041eb808599e19">HBM954.NBFJ.868</a></li></ul><br><li>Invalid: 1</li>The dataset cannot be validated due a metadata or directory issue. View the errors on the dataset ingest page and correct them. Help is available by scheduling with Data Curator Brendan Honick (https://calendly.com/bhonick-psc/).<br><ul><li><a href="https://ingest.hubmapconsortium.org/Dataset/ffb964a87cd93bc110ba39884d7df42a">HBM658.VMWF.882</a></li></ul><br><li>New: 1</li>This status is an artifact of prior status handling. Go to the dataset ingest page and press "Submit."<br><ul><li><a href="https://ingest.hubmapconsortium.org/Dataset/474f0b4a77083fe938cc9352cb9a9470">HBM328.ZSPV.447</a></li></ul><br></ul><br><b>Datasets currently in the ingestion process:</b><br>Below are counts of datasets not currently requiring action on your part, with a brief description of each status.<br><ul><li>Error: 1</li>Datasets have encountered an internal HIVE error. Curators and developers are working to address the issue.<br><ul><li><a href="https://ingest.hubmapconsortium.org/Dataset/889a27e6521388e3553472fc9e14439d">HBM654.VCSC.832</a></li></ul><br></ul>Please consult our <a href="https://docs.google.com/document/d/13zBbp_BNCVPZPj71Q5dGLoNJ_TDRyEpPck2mGQbkLYg/edit?usp=sharing">guide to HuBMAP entity statuses</a> if you would like to learn more about the different dataset statuses.<br>'
