version: "3.7"

services:

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - gateway_hubmap


  ingest-pipeline:
    build: ./ingest-pipeline
    # Build the image with name and tag
    image: ingest-pipeline:0.2
    restart: always
    depends_on:
      - postgres
    hostname: ingest-pipeline
    container_name: ingest-pipeline
    volumes:
      # Mount dags, plugins, and data
      - "../src/ingest-pipeline/airflow/dags:/opt/airflow/dags:rw"
      - "../src/ingest-pipeline/airflow/lib:/opt/airflow/lib:rw"
      - "../src/ingest-pipeline/airflow/plugins:/opt/airflow/plugins:rw"
      - "../src/ingest-pipeline/airflow/data:/opt/airflow/data:rw"
      - "../src/ingest-pipeline/instance:/opt/airflow/instance"
      # Mount requirements.txt
      - "../src/ingest-pipeline/requirements.txt:/requirements.txt"
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - AIRFLOW__HUBMAP_API_PLUGIN__BUILD_NUMBER=${INGEST_PIPELINE_BUILD_NUM:-0}
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - COMMONS_BRANCH=${COMMONS_BRANCH:-master}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - gateway_hubmap
    ports:
      - "8789:8789"
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
     

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  gateway_hubmap:
    external: true
