version: "3.7"

services:
  
  ingest-pipeline:
    volumes:
      # Mount the source code to container.  This includes the instance/app.cfg file
      # one directory below.
      - "../src/ingest-pipeline:/usr/src/app/src"
      # Map the actual root of the staging area to container
      - "/hubmap-data:/usr/local/airflow/lz"
    environment:
      - AIRFLOW_CONN_INGEST_API_CONNECTION=http://hubmap-auth:4444/
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8789
      - FLASK_RUN_PORT=8789



